### ISSUE TITLE
lease offload RPC query.

### ISSUE THREAD

**Issue by matsuro-hadouken** [ovrclk/ecosystem#521]
I'm calling my active lease on **edgenet-1**

`akash query market lease list --owner $ACCOUNT_ADDRESS --node $AKASH_NODE --state active`

Output:

```
leases:
- lease_id:
    dseq: "156861"
    gseq: 1
    oseq: 1
    owner: akash1ypme9rxu9hx8qprgpmvnwpp0lztzjwvcsqkcfz
    provider: akash174hxdpuxsuys9qkauaf57ym5j8dm4secnz6jd7
  price:
    amount: "842"
    denom: uakt
  state: active
pagination:
  next_key: null
  total: "0"
```

Query RPC port, call active lease again:

```
leases: []
pagination:
  next_key: null
  total: "0"
```
Ask proivider for the log output:

```
akash \
>   --home "$AKASH_HOME" \
>   --node "$AKASH_NODE" \
>   provider service-logs \
>   --service $SERVICE_NAME \
>   --owner "$ACCOUNT_ADDRESS" \
>   --dseq "$DSEQ" \
>   --gseq 1 \
>   --oseq $OSEQ \
>   --provider "$PROVIDER"
```
Log output:

```
panic: could not create directory : mkdir : no such file or directory

goroutine 1 [running]:
github.com/tendermint/tendermint/config.EnsureRoot(0x0, 0x0)
        github.com/tendermint/tendermint@v0.34.0-rc6/config/toml.go:35 +0x305
github.com/cosmos/cosmos-sdk/server.interceptConfigs(0xc0010c0ea0, 0xc00110f6c0, 0x4, 0xc000da99b8)
        github.com/cosmos/cosmos-sdk@v0.40.0-rc3/server/util.go:152 +0x846
github.com/cosmos/cosmos-sdk/server.InterceptConfigsPreRunHandler(0xc001097b80, 0x0, 0x0)
        github.com/cosmos/cosmos-sdk@v0.40.0-rc3/server/util.go:90 +0x2ef
github.com/ovrclk/akash/cmd/akash/cmd.NewRootCmd.func1(0xc001097b80, 0xc001198000, 0x1, 0xf, 0x0, 0x0)
        github.com/ovrclk/akash/cmd/akash/cmd/root.go:64 +0xce
github.com/tendermint/tendermint/libs/cli.concatCobraCmdFuncs.func1(0xc001097b80, 0xc001198000, 0x1, 0xf, 0x0, 0x0)
        github.com/tendermint/tendermint@v0.34.0-rc6/libs/cli/setup.go:118 +0x7d
github.com/spf13/cobra.(*Command).execute(0xc001097b80, 0xc000e6bef0, 0xf, 0xf, 0xc001097b80, 0xc000e6bef0)
        github.com/spf13/cobra@v1.1.1/command.go:829 +0x587
github.com/spf13/cobra.(*Command).ExecuteC(0xc001096840, 0x28aafac, 0x5, 0xc000e817e0)
        github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.1/command.go:895
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.1.1/command.go:888
github.com/ovrclk/akash/cmd/akash/cmd.Execute(0xc001096840, 0x2e495a0, 0xc001075960)
        github.com/ovrclk/akash/cmd/akash/cmd/root.go:89 +0x22f
main.main()
        github.com/ovrclk/akash/cmd/akash/main.go:12 +0x2a
```

Expected:

No error in a log, leas stay active provide all functionality.
